development:
  adapter: mysql2
  encoding: utf8
  database: sala_extraccion_dev
  pool: 5
  username: root
  password: dev

test:
  adapter: mysql2
  encoding: utf8
  database: sala_extraccion_test
  pool: 5
  username: root
  password: dev

production:
  adapter: mysql2
  encoding: utf8
  database: sala_extraccion_production
  pool: 5
  username: root
  password: dev
